### ISSUE TITLE
WebDriverException: Message: 'geckodriver' executable needs to be in PATH even though  'geckodriver' is in PATH

### ISSUE THREAD

**Issue by cpk011** [nokia/RED#287]
Hi.

I get an error that 'geckodriver' executable is not in PATH even though it is.
I am running RED on macOS Mojave 14.10.4.

In addition, the console message had:

Command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -m robot.run --listener /var/folders/14/tc2fv6dx3n3gpxnm5n77htd80000gn/T/RobotTempDir5703327076939529327/TestRunnerAgent.py:54972 --argumentfile /var/folders/14/tc2fv6dx3n3gpxnm5n77htd80000gn/T/RobotTempDir5703327076939529327/args_35cd706d.arg /Users/peter/eclipse-workspace/some-project-name
Suite Executor: Robot Framework 3.1.1 (Python 3.7.2 on darwin)

Same for chromedriver.

Peter

**Comment by joanna-may** [comment]
Hi,

can you check this:
https://github.com/nokia/RED/issues/89
https://github.com/nokia/RED/issues/285

**Comment by cpk011** [comment]
Thank you.

I did Log  %{PATH} to find out that it was different from the $PATH in macOS.

Peter

**Comment by cpk011** [comment]
I was able to set environment variable PATH within RobotFramework to include /usr/local/bin where geckodriver and chromedriver are installed. Now I am getting a similar error message from SeleniumLibrary.

<img width="822" alt="Screen Shot 2019-04-01 at 8 47 35 AM" src="https://user-images.githubusercontent.com/25830321/55328676-e65aa200-545a-11e9-85fb-b215ddd4061e.png">

**Comment by joanna-may** [comment]
I see in your screen path: "/user/**loca**/bin". If that is not a problem there were some similar problems with this path in:
https://github.com/nokia/RED/issues/285
Try maybe move driver to other location and check if it helps. This error is only from Selenium - RED is only running test

**Comment by nunessf** [comment]
Hi! I am using Windows, and I have the same problem.
When logging %{PATH}, one of the values is "%PYTHONPATH%". And when logging %{PYTHONPATH},  I can see it contains the folder where the executable is.
When running the tests through the command line and not from RED, it works.
I also noticed that the argument file that is being generated contains a pythonpath variable with values that don't match the environment variable.

**Comment by joanna-may** [comment]
Hi,
it is not working running selenium test with Chromdriver? If yes where it is installed? What error is on Console/Message Log?

RED in argument file is only extending PYTHONPATH so it is your system PYTHONPATH + paths that are in red.xml -> Libraries -> Paths

**Comment by nunessf** [comment]
Yes. Chromedriver is at C:\Python36\Scripts, and that path is in red.xml, as shown below.

![Screenshot_1](https://user-images.githubusercontent.com/45309185/56959664-170b2580-6b46-11e9-8d38-ce14f3192c8c.png)

The exception is this one, as if  the chromedriver was not in that folder: 

`WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

However, when running the tests through the command line, the chromedriver is found and it runs okay.

**Comment by joanna-may** [comment]
I added all as you and when I run test by RED Chrome is opened en test is pass. I added at the end of PATH: ;%PYTHONPATH%".
![paths](https://user-images.githubusercontent.com/15103418/56967233-1f248e80-6b61-11e9-94c2-a281c71fd3ee.JPG)

Can you check in console "echo %PATH" that %PYTHONPATH% is resolved to "..;C:\Python36;C:\Python36\Scripts"

Despite paths it is wrong to add path of python executable to PYTHONPATH. This variable should be set to add additional directories where python will look for modules and packages. And C:\Python36\Scripts  is not the best place to keep chromedriver - is internal python folder

**Comment by nunessf** [comment]
Yes, when checking "echo %PATH%" in the console, the first results of the path are "C:\Python36\;C:\Python36\Scripts\;"

However, when running "Log    %{PATH}" through Robot Framework, I can see that the PYTHONPATH is not resolved to any path, it just literally prints %PYTHONPATH% among the rest of the paths.

Thanks for the advice on the rest

**Comment by joanna-may** [comment]
There must be something with resolving Pythonpath. I see in my Message log correct resolved path. You said that paths are incorrect in argument file - what it contains?

**Comment by nunessf** [comment]
Yes, the argument file generated contains the following as pythonpath:
- The location of a custom library
- C:\Python36\Lib\site-packages

**Comment by joanna-may** [comment]
Hi,
any news about this problem? If it persists, can you copy output from window in Help -> About Red -> Installation Details -> Configuration tab?
In my opinion you can try to move driver to any location and add this path to PATH. Remove Python location from PYTHONPATH and this variable from PATH and check if it is works.

**Comment by michalanglart** [comment]
I'm closing it now. If the problem would still occur please have a look at #332 as it seems to be very similar
